$path = "c:\midia_igreja\app\admin\escalas\[id]\voluntarios\page.tsx"
$content = [System.IO.File]::ReadAllText($path, [System.Text.Encoding]::UTF8)

# Fix 1: publicadaInfo.dados.slots at line 1271 (in the dead-code false block)
# Replace specifically in the second occurrence (inside {false && ...} block)
$old1 = "        const slotsData = publicadaInfo.dados.slots" + [char]10 + "        const byPersonMsg: Record<string, { name: string; pSlots: Array<{ label: string; date: string; time: string; funcao: string }> }> = {}" + [char]10 + "        for (const slot of slotsData) {" + [char]10 + "          for (const a of slot.assignments) {" + [char]10 + "            if (!byPersonMsg[a.person_id]) byPersonMsg[a.person_id] = { name: a.person_name, pSlots: [] }" + [char]10 + "            byPersonMsg[a.person_id].pSlots.push({ label: slot.label, date: slot.date, time: slot.time_of_day, funcao: a.funcao })" + [char]10 + "          }" + [char]10 + "        }" + [char]10 + "        const slotsOrdenados = [...slotsData]" + [char]10 + "          .filter(s => s.assignments.length > 0)" + [char]10 + "          .sort((a, b) => a.date.localeCompare(b.date) || a.time_of_day.localeCompare(b.time_of_day))" + [char]10 + "" + [char]10 + "        const totalMsgs = previewTipo === 'mes'" + [char]10 + "          ? Object.keys(byPersonMsg).length" + [char]10 + "          : slotsOrdenados.reduce((acc, s) => acc + new Set(s.assignments.map(a => a.person_id)).size, 0)" + [char]10 + "" + [char]10 + "        return (" + [char]10 + "          <div className=""mx-6 md:mx-8 mb-8 bg-white rounded-2xl border border-slate-200 shadow-sm"">"

$new1 = "        const slotsData = publicadaInfo?.dados?.slots ?? []" + [char]10 + "        const byPersonMsg: Record<string, { name: string; pSlots: Array<{ label: string; date: string; time: string; funcao: string }> }> = {}" + [char]10 + "        for (const slot of slotsData) {" + [char]10 + "          for (const a of slot.assignments) {" + [char]10 + "            if (!byPersonMsg[a.person_id]) byPersonMsg[a.person_id] = { name: a.person_name, pSlots: [] }" + [char]10 + "            byPersonMsg[a.person_id].pSlots.push({ label: slot.label, date: slot.date, time: slot.time_of_day, funcao: a.funcao })" + [char]10 + "          }" + [char]10 + "        }" + [char]10 + "        const slotsOrdenados = [...slotsData]" + [char]10 + "          .filter(s => s.assignments.length > 0)" + [char]10 + "          .sort((a, b) => a.date.localeCompare(b.date) || a.time_of_day.localeCompare(b.time_of_day))" + [char]10 + "" + [char]10 + "        const totalMsgs = previewTipo === 'mes'" + [char]10 + "          ? Object.keys(byPersonMsg).length" + [char]10 + "          : slotsOrdenados.reduce((acc, s) => acc + new Set(s.assignments.map(a => a.person_id)).size, 0)" + [char]10 + "" + [char]10 + "        return (" + [char]10 + "          <div className=""mx-6 md:mx-8 mb-8 bg-white rounded-2xl border border-slate-200 shadow-sm"">"

Write-Host "old1 found: $($content.IndexOf($old1) -ge 0)"
